api:
  host: "0.0.0.0"
  port: 8000
  debug: true
  reload: true

database:
  url: "sqlite:///./dev_database.db"

llm:
  model_name: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 150

embedding:
  model_name: "text-embedding-ada-002"

vector_store:
  type: "faiss"
  index_path: "./dev_faiss_index"

document_processing:
  chunk_size: 1000
  chunk_overlap: 200

observability:
  log_level: "DEBUG"
  otlp_endpoint: "http://localhost:4317"
  enable_metrics: true
  enable_tracing: true

security:
  secret_key: "dev_secret_key_change_in_production"
  access_token_expire_minutes: 30

rate_limiting:
  enabled: false

caching:
  enabled: false